# Generated by Django 3.2.6 on 2021-08-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_account', '0003_remove_customeraccount_email'),
        ('product_health', '0002_auto_20210831_1652'),
        ('products', '0003_auto_20210805_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('order_number', models.CharField(
                    editable=False,
                    max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(
                    blank=True,
                    max_length=20)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(
                    blank=True,
                    max_length=80)),
                ('county', models.CharField(
                    blank=True,
                    max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    max_digits=6)),
                ('order_total', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    max_digits=10)),
                ('grand_total', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    max_digits=10)),
                ('customer_account', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='orders',
                    to='customer_account.customeraccount'
                    )),
                ('purchase_history', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='also_bought',
                    to='product_health.purchasehistory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(
                    decimal_places=2,
                    editable=False,
                    max_digits=6)),
                ('order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='lineitems',
                    to='checkout.order')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='products.product')),
            ],
        ),
    ]
