# Generated by Django 3.2.6 on 2021-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(
                choices=[(1, '1'),
                         (2, '2'),
                         (3, '3'),
                         (4, '4'),
                         (5, '5')], default=5),
        ),
    ]
