# Generated by Django 3.2.6 on 2021-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """Customer account name field change"""
    dependencies = [
        ('customer_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='full_name',
            field=models.CharField(
                blank=True,
                max_length=80),
        ),
    ]
