# Generated by Django 3.2.6 on 2021-08-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0002_customeraccount_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='email',
        ),
    ]
