# Generated by Django 3.2.6 on 2021-08-05 15:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(
                default='No Image',
                max_length=255,
                verbose_name='image'),
        ),
    ]
