# Generated by Django 3.2.6 on 2021-08-10 21:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='No Image', max_length=255, verbose_name='image'),
        ),
    ]
